### ISSUE TITLE
<2.0.0 builds resolve to 2.0.0 on pypi pulls

### ISSUE THREAD

**Issue by crawfobw** [MousaZeidBaker/aws-lambda-typing#15] opened 2021-08-23 22:40 UTC
First want to say, love the project, thanks for maintaining for community.

Just wanted to give a heads up that it appears prior versions of the project when specified in a requirements.txt ex 1.0.3 result in actually pulling 2.0.0.

**Comment by MousaZeidBaker** [comment] 2021-08-24 09:02
Hi @crawfobw, glad you like the project!

Thanks for the head up. I don't think the issue is with `aws-lambda-typing` but rather with your package resolver. All prior versions exist in pypi and are never removed nor changed. I have previously tested to lock a specific version with `poetry` without any issues.  I can give `pip` a try once I get back from my vacation.

**Comment by MousaZeidBaker** [comment] 2021-09-01 14:11
Hi again,

I could successfully install an old version of the package with pip without any issues, see below screenshots, so I'm closing this issue now. 

Installing directly from the CLI
![pip](https://user-images.githubusercontent.com/16031346/131685383-8f34470d-1478-4334-a57c-df5b519b619e.png)

Installing from requirements.txt
![pip](https://user-images.githubusercontent.com/16031346/131686430-0d694546-bb14-4546-8fc2-8f79c5a14a26.png)

**Closed by MousaZeidBaker** 2021-09-01 14:11 UTC
